# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_invited', models.EmailField(max_length=254)),
                ('user_has_signed_up', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
