# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_signupinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupinvitation',
            old_name='created_at',
            new_name='created_att',
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
