# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_signupwaitinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
