# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171013_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupinvitation',
            name='created_att',
        ),
        migrations.AddField(
            model_name='signupinvitation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 10, 13, 2, 45, 41, 59893)),
        ),
    ]
