# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171013_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinvitation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signupinvitation',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
