# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0006_auto_20171229_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='actual_city',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_city', to='events.City'),
        ),
    ]
