# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-28 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('place_id', models.CharField(max_length=300, unique=True)),
                ('image', models.CharField(max_length=300, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('expected_costs', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City')),
                ('hosted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('place_id', models.CharField(max_length=300, unique=True)),
                ('image', models.CharField(max_length=300, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Location'),
        ),
    ]
