# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palindrome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=500)),
                ('is_palindrome', models.BooleanField()),
            ],
        ),
    ]
