# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
