# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171108_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
