# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 01:51
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=''),
        ),
    ]
