# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171025_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
