#!/bin/bash
heroku config:set DATABASE_NAME=$DATABASE_NAME
heroku config:set DATABASE_USER=$DATABASE_USER
heroku config:set DATABASE_PASSWORD=$DATABASE_PASSWORD
heroku config:set DATABASE_HOST=$DATABASE_HOST
heroku config:set DATABASE_PORT=$DATABASE_PORT
heroku config:set SOCIAL_AUTH_FACEBOOK_KEY=$SOCIAL_AUTH_FACEBOOK_KEY
heroku config:set SOCIAL_AUTH_FACEBOOK_SECRET=$SOCIAL_AUTH_FACEBOOK_SECRET
heroku config:set EMAIL_HOST=$EMAIL_HOST
heroku config:set EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
heroku config:set EMAIL_HOST_USER=$EMAIL_HOST_USER
heroku config:set EMAIL_PORT=$EMAIL_PORT
heroku config:set DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE